// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: api/sdk/v1/sdk.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *CommonReply) Reset() {
	*x = CommonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sdk_v1_sdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReply) ProtoMessage() {}

func (x *CommonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_sdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReply.ProtoReflect.Descriptor instead.
func (*CommonReply) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *CommonReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CommonReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type InitSdkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId uint32       `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Data  *InitSdkData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sign  string       `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *InitSdkReq) Reset() {
	*x = InitSdkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sdk_v1_sdk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitSdkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSdkReq) ProtoMessage() {}

func (x *InitSdkReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_sdk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSdkReq.ProtoReflect.Descriptor instead.
func (*InitSdkReq) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *InitSdkReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *InitSdkReq) GetData() *InitSdkData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InitSdkReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type InitSdkData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Udid    string `protobuf:"bytes,1,opt,name=udid,proto3" json:"udid,omitempty"`
	Channel uint32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *InitSdkData) Reset() {
	*x = InitSdkData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sdk_v1_sdk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitSdkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSdkData) ProtoMessage() {}

func (x *InitSdkData) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_sdk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSdkData.ProtoReflect.Descriptor instead.
func (*InitSdkData) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *InitSdkData) GetUdid() string {
	if x != nil {
		return x.Udid
	}
	return ""
}

func (x *InitSdkData) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type InitSdkReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"` //  string gameName = 3; // 暂不返回，因为要单独拿数据
}

func (x *InitSdkReply) Reset() {
	*x = InitSdkReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sdk_v1_sdk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitSdkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSdkReply) ProtoMessage() {}

func (x *InitSdkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_sdk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSdkReply.ProtoReflect.Descriptor instead.
func (*InitSdkReply) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *InitSdkReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InitSdkReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CheckEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId uint32 `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Data  string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sign  string `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *CheckEnterReq) Reset() {
	*x = CheckEnterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sdk_v1_sdk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEnterReq) ProtoMessage() {}

func (x *CheckEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_sdk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEnterReq.ProtoReflect.Descriptor instead.
func (*CheckEnterReq) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *CheckEnterReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CheckEnterReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CheckEnterReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

var File_api_sdk_v1_sdk_proto protoreflect.FileDescriptor

var file_api_sdk_v1_sdk_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x64, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0b,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5f, 0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x64, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x64, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x3b, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x64,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x64, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x22, 0x34, 0x0a, 0x0c, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x64, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4d, 0x0a, 0x0d, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x32, 0xb2, 0x01, 0x0a, 0x03, 0x53, 0x64, 0x6b,
	0x12, 0x54, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x64, 0x6b, 0x12, 0x12, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x64, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x64, 0x6b,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x14, 0x2f,
	0x73, 0x64, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x69, 0x74, 0x5f,
	0x73, 0x64, 0x6b, 0x3a, 0x01, 0x2a, 0x12, 0x55, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x73, 0x64,
	0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x3a, 0x01, 0x2a, 0x42, 0x34, 0x0a,
	0x15, 0x64, 0x65, 0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x53, 0x64, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x56, 0x31, 0x50, 0x01, 0x5a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sdk_v1_sdk_proto_rawDescOnce sync.Once
	file_api_sdk_v1_sdk_proto_rawDescData = file_api_sdk_v1_sdk_proto_rawDesc
)

func file_api_sdk_v1_sdk_proto_rawDescGZIP() []byte {
	file_api_sdk_v1_sdk_proto_rawDescOnce.Do(func() {
		file_api_sdk_v1_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sdk_v1_sdk_proto_rawDescData)
	})
	return file_api_sdk_v1_sdk_proto_rawDescData
}

var file_api_sdk_v1_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_sdk_v1_sdk_proto_goTypes = []interface{}{
	(*CommonReply)(nil),   // 0: sdk.v1.CommonReply
	(*InitSdkReq)(nil),    // 1: sdk.v1.InitSdkReq
	(*InitSdkData)(nil),   // 2: sdk.v1.InitSdkData
	(*InitSdkReply)(nil),  // 3: sdk.v1.InitSdkReply
	(*CheckEnterReq)(nil), // 4: sdk.v1.CheckEnterReq
}
var file_api_sdk_v1_sdk_proto_depIdxs = []int32{
	2, // 0: sdk.v1.InitSdkReq.data:type_name -> sdk.v1.InitSdkData
	1, // 1: sdk.v1.Sdk.InitSdk:input_type -> sdk.v1.InitSdkReq
	4, // 2: sdk.v1.Sdk.CheckEnter:input_type -> sdk.v1.CheckEnterReq
	3, // 3: sdk.v1.Sdk.InitSdk:output_type -> sdk.v1.InitSdkReply
	0, // 4: sdk.v1.Sdk.CheckEnter:output_type -> sdk.v1.CommonReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_sdk_v1_sdk_proto_init() }
func file_api_sdk_v1_sdk_proto_init() {
	if File_api_sdk_v1_sdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sdk_v1_sdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sdk_v1_sdk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitSdkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sdk_v1_sdk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitSdkData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sdk_v1_sdk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitSdkReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sdk_v1_sdk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEnterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sdk_v1_sdk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sdk_v1_sdk_proto_goTypes,
		DependencyIndexes: file_api_sdk_v1_sdk_proto_depIdxs,
		MessageInfos:      file_api_sdk_v1_sdk_proto_msgTypes,
	}.Build()
	File_api_sdk_v1_sdk_proto = out.File
	file_api_sdk_v1_sdk_proto_rawDesc = nil
	file_api_sdk_v1_sdk_proto_goTypes = nil
	file_api_sdk_v1_sdk_proto_depIdxs = nil
}
