// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.0

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type SdkHTTPServer interface {
	CheckEnter(context.Context, *CheckEnterRequest) (*CheckEnterReply, error)
}

func RegisterSdkHTTPServer(s *http.Server, srv SdkHTTPServer) {
	r := s.Route("/")
	r.POST("/sdk/check_enter", _Sdk_CheckEnter0_HTTP_Handler(srv))
}

func _Sdk_CheckEnter0_HTTP_Handler(srv SdkHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckEnterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/sdk.v1.Sdk/CheckEnter")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckEnter(ctx, req.(*CheckEnterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckEnterReply)
		return ctx.Result(200, reply)
	}
}

type SdkHTTPClient interface {
	CheckEnter(ctx context.Context, req *CheckEnterRequest, opts ...http.CallOption) (rsp *CheckEnterReply, err error)
}

type SdkHTTPClientImpl struct {
	cc *http.Client
}

func NewSdkHTTPClient(client *http.Client) SdkHTTPClient {
	return &SdkHTTPClientImpl{client}
}

func (c *SdkHTTPClientImpl) CheckEnter(ctx context.Context, in *CheckEnterRequest, opts ...http.CallOption) (*CheckEnterReply, error) {
	var out CheckEnterReply
	pattern := "/sdk/check_enter"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/sdk.v1.Sdk/CheckEnter"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
