// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SdkClient is the client API for Sdk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SdkClient interface {
	// 激活
	// 支持rpc与http
	InitSdk(ctx context.Context, in *InitSdkReq, opts ...grpc.CallOption) (*InitSdkReply, error)
	// 用户名注册
	Reg(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegReply, error)
	// 用户名登录
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error)
	// 验证进入游戏
	CheckEnter(ctx context.Context, in *CheckEnterReq, opts ...grpc.CallOption) (*CommonReply, error)
}

type sdkClient struct {
	cc grpc.ClientConnInterface
}

func NewSdkClient(cc grpc.ClientConnInterface) SdkClient {
	return &sdkClient{cc}
}

func (c *sdkClient) InitSdk(ctx context.Context, in *InitSdkReq, opts ...grpc.CallOption) (*InitSdkReply, error) {
	out := new(InitSdkReply)
	err := c.cc.Invoke(ctx, "/sdk.v1.Sdk/InitSdk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) Reg(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegReply, error) {
	out := new(RegReply)
	err := c.cc.Invoke(ctx, "/sdk.v1.Sdk/Reg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/sdk.v1.Sdk/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdkClient) CheckEnter(ctx context.Context, in *CheckEnterReq, opts ...grpc.CallOption) (*CommonReply, error) {
	out := new(CommonReply)
	err := c.cc.Invoke(ctx, "/sdk.v1.Sdk/CheckEnter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdkServer is the server API for Sdk service.
// All implementations must embed UnimplementedSdkServer
// for forward compatibility
type SdkServer interface {
	// 激活
	// 支持rpc与http
	InitSdk(context.Context, *InitSdkReq) (*InitSdkReply, error)
	// 用户名注册
	Reg(context.Context, *RegReq) (*RegReply, error)
	// 用户名登录
	Login(context.Context, *LoginReq) (*LoginReply, error)
	// 验证进入游戏
	CheckEnter(context.Context, *CheckEnterReq) (*CommonReply, error)
	mustEmbedUnimplementedSdkServer()
}

// UnimplementedSdkServer must be embedded to have forward compatible implementations.
type UnimplementedSdkServer struct {
}

func (UnimplementedSdkServer) InitSdk(context.Context, *InitSdkReq) (*InitSdkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitSdk not implemented")
}
func (UnimplementedSdkServer) Reg(context.Context, *RegReq) (*RegReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reg not implemented")
}
func (UnimplementedSdkServer) Login(context.Context, *LoginReq) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSdkServer) CheckEnter(context.Context, *CheckEnterReq) (*CommonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEnter not implemented")
}
func (UnimplementedSdkServer) mustEmbedUnimplementedSdkServer() {}

// UnsafeSdkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SdkServer will
// result in compilation errors.
type UnsafeSdkServer interface {
	mustEmbedUnimplementedSdkServer()
}

func RegisterSdkServer(s grpc.ServiceRegistrar, srv SdkServer) {
	s.RegisterService(&Sdk_ServiceDesc, srv)
}

func _Sdk_InitSdk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSdkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).InitSdk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.v1.Sdk/InitSdk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).InitSdk(ctx, req.(*InitSdkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_Reg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).Reg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.v1.Sdk/Reg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).Reg(ctx, req.(*RegReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.v1.Sdk/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sdk_CheckEnter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEnterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdkServer).CheckEnter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.v1.Sdk/CheckEnter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdkServer).CheckEnter(ctx, req.(*CheckEnterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sdk_ServiceDesc is the grpc.ServiceDesc for Sdk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sdk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdk.v1.Sdk",
	HandlerType: (*SdkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitSdk",
			Handler:    _Sdk_InitSdk_Handler,
		},
		{
			MethodName: "Reg",
			Handler:    _Sdk_Reg_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Sdk_Login_Handler,
		},
		{
			MethodName: "CheckEnter",
			Handler:    _Sdk_CheckEnter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/sdk/v1/sdk.proto",
}
